name: db
channels:
  - soumith
  - defaults
  - conda-forge
  - pytorch
  - torch
dependencies:
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.2=py37hecd8cb5_1001
  - arrow-cpp=4.0.1=py37hf7c73f6_3
  - astroid=2.9.0=py37hecd8cb5_0
  - atk-1.0=2.36.0=hb642b71_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - aws-c-common=0.4.57=hb1e8313_1
  - aws-c-event-stream=0.1.6=h23ab428_5
  - aws-checksums=0.1.9=hb1e8313_0
  - aws-sdk-cpp=1.8.185=he271ece_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.zoneinfo=0.2.1=py37h271585c_4
  - bcrypt=3.2.0=py37haf1e3a3_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - boost-cpp=1.73.0=h9ed2024_11
  - bottleneck=1.3.4=py37h67323c0_0
  - brotli=1.0.9=hb1e8313_2
  - brotlipy=0.7.0=py37h9ed2024_1003
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.18.1=hca72f7f_0
  - ca-certificates=2022.3.29=hecd8cb5_0
  - cairo=1.16.0=h8023c5d_1
  - certifi=2021.10.8=py37hecd8cb5_2
  - cffi=1.15.0=py37hc55c11b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py37hecd8cb5_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - codecov=2.1.11=pyhd3eb1b0_0
  - coverage=6.3.2=py37hca72f7f_0
  - cryptography=36.0.0=py37hf6deb26_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.5.1=py37he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.4=pyhd3eb1b0_0
  - doit=0.33.1=py37hecd8cb5_0
  - double-conversion=3.1.5=haf313ee_1
  - entrypoints=0.3=py37_0
  - expat=2.4.4=he9d5cce_2
  - ffmpeg=4.3=h0a44026_0
  - flake8=4.0.1=pyhd3eb1b0_0
  - flask=2.0.2=pyhd3eb1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.13.1=ha9ee91d_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.11.0=hd8bbffd_0
  - fribidi=1.0.10=haf1e3a3_0
  - g-ir-build-tools=1.72.0=py37hc9550b4_1
  - g-ir-host-tools=1.72.0=h5734cbb_1
  - gdk-pixbuf=2.42.6=h712c34a_5
  - gettext=0.21.0=h7535e17_0
  - gflags=2.2.2=h0a44026_0
  - giflib=5.2.1=haf1e3a3_0
  - glib=2.70.2=hcf210ce_4
  - glib-tools=2.70.2=hcf210ce_4
  - glog=0.5.0=h23ab428_0
  - gmp=6.2.1=h23ab428_2
  - gnutls=3.6.15=hed9c0bf_0
  - gobject-introspection=1.72.0=py37hc941436_1
  - graphite2=1.3.14=h38d11af_0
  - graphviz=2.50.0=h77de9ca_1
  - grpc-cpp=1.26.0=h044775b_0
  - gtk2=2.24.33=h675d97a_1
  - gts=0.7.6=h6759243_3
  - harfbuzz=3.1.2=he73883e_0
  - icu=58.2=h0a44026_3
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - ipykernel=6.9.0=py37h4c52d7d_0
  - ipython=7.31.1=py37hecd8cb5_0
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jedi=0.18.1=py37hecd8cb5_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h9ed2024_0
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py37hecd8cb5_0
  - krb5=1.19.2=hcd88c3b_0
  - lame=3.100=h1de35cc_0
  - lazy-object-proxy=1.6.0=py37h9ed2024_0
  - lcms2=2.12=hf1fd2bf_0
  - libboost=1.73.0=hd4c2dcd_11
  - libcurl=7.80.0=h6dfd666_0
  - libcxx=12.0.0=h2f01273_0
  - libedit=3.1.20210910=hca72f7f_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.12=h0a4fc7d_0
  - libffi=3.4.2=he9d5cce_2
  - libgd=2.3.3=he7e2580_0
  - libgfortran=3.0.1=h93005f0_2
  - libgirepository=1.72.0=h0bde3a9_1
  - libglib=2.70.2=hf1fb8c0_4
  - libiconv=1.16=h1de35cc_0
  - libidn2=2.3.2=h9ed2024_0
  - libnghttp2=1.46.0=ha29bfda_0
  - libpng=1.6.37=ha441bb4_0
  - libpq=14.2=hea3049e_0
  - libprotobuf=3.11.2=hd9629dc_0
  - librsvg=2.52.5=h02b643e_1
  - libsodium=1.0.18=h1de35cc_0
  - libssh2=1.9.0=ha12b0ac_1
  - libtasn1=4.16.0=h9ed2024_0
  - libthrift=0.13.0=h054ceb0_6
  - libtiff=4.2.0=h87d7836_0
  - libtool=2.4.6=he9d5cce_1008
  - libunistring=0.9.10=h9ed2024_0
  - libuv=1.40.0=haf1e3a3_0
  - libwebp=1.2.2=h56c3ce4_0
  - libwebp-base=1.2.2=hca72f7f_0
  - libxml2=2.9.12=hcdb78fc_0
  - libzlib=1.2.11=h6c3fc93_1014
  - lightgbm=3.2.1=py37h23ab428_0
  - llvm-openmp=12.0.0=h0dcd299_1
  - lz4-c=1.9.3=h23ab428_1
  - macfsevents=0.8.1=py37h9ed2024_0
  - markupsafe=2.0.1=py37h9ed2024_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py37_1
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py37h9ed2024_0
  - mkl_fft=1.3.1=py37h4ab4a9b_0
  - mkl_random=1.2.2=py37hb2f4e1b_0
  - mypy_extensions=0.4.3=py37hecd8cb5_1
  - ncurses=6.3=hca72f7f_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.7.3=h230ac6f_1
  - ninja=1.10.2=py37haf03e11_3
  - numexpr=2.8.1=py37h2e5f0a9_0
  - numpy=1.21.2=py37h4b4dc7a_0
  - numpy-base=1.21.2=py37he0bd621_0
  - openh264=2.1.1=h8346a28_0
  - openssl=1.1.1n=hca72f7f_0
  - orc=1.6.7=h001ef8f_2
  - packaging=21.3=pyhd3eb1b0_0
  - pandarallel=1.5.5=pyhd8ed1ab_0
  - pandas=1.3.5=py37h743cdd8_0
  - pango=1.48.10=h056538c_2
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathlib=1.0.1=py37_1
  - pathspec=0.7.0=py_0
  - pcre=8.45=h23ab428_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.2=py37hecd8cb5_0
  - pixman=0.40.0=h9ed2024_1
  - pkg-config=0.29.2=h3efe00b_8
  - platformdirs=2.4.0=pyhd3eb1b0_0
  - plumbum=1.7.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.8.0=py37h9ed2024_1
  - psycopg=3.0.8=py37hf985489_0
  - psycopg-c=3.0.8=py37h271585c_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyarrow=4.0.1=py37hdf3e9eb_3
  - pycparser=2.21=pyhd3eb1b0_0
  - pydotplus=2.0.2=py_3
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyhdb=0.3.4=py_0
  - pylint=2.12.2=py37hecd8cb5_0
  - pynacl=1.4.0=py37haf1e3a3_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pysocks=1.7.1=py37hecd8cb5_0
  - python=3.7.12=haf480d7_100_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.11.0=py3.7_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pyzmq=22.3.0=py37he9d5cce_2
  - re2=2020.11.01=h23ab428_1
  - readline=8.1.2=hca72f7f_1
  - regex=2022.3.15=py37hca72f7f_0
  - requests=2.27.1=pyhd3eb1b0_0
  - scikit-learn=1.0.2=py37hae1ba45_1
  - scipy=1.7.3=py37h8c7af03_0
  - setproctitle=1.2.2=py37h9ed2024_1004
  - setuptools=58.0.4=py37hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.8=hb1e8313_0
  - sqlite=3.38.2=h707629a_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h7bc2e8c_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.11.0=py37_cpu
  - torchvision=0.12.0=py37_cpu
  - tornado=6.1=py37h9ed2024_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.4.3=py37h9ed2024_1
  - types-pyyaml=6.0.4=pyhd8ed1ab_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - uriparser=0.9.3=h0a44026_1
  - urllib3=1.26.8=pyhd3eb1b0_0
  - utf8proc=2.6.1=h9ed2024_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.13.3=py37hca72f7f_2
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h6c3fc93_1014
  - zstd=1.4.9=h322a384_0
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - category-encoders==2.4.0
    - colorama==0.4.4
    - colorlog==6.6.0
    - cycler==0.11.0
    - cython==0.29.28
    - dask==2021.12.0
    - defusedxml==0.7.1
    - distributed==2021.12.0
    - easydev==0.12.0
    - featurewiz==0.1.0
    - fitter==1.4.0
    - fonttools==4.30.0
    - fsspec==2022.2.0
    - heapdict==1.0.1
    - imbalanced-learn==0.9.0
    - importlib-metadata==4.2.0
    - importlib-resources==5.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jmespath==0.9.4
    - joypy==0.2.6
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-console==6.4.3
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.4.0
    - locket==0.2.1
    - matplotlib==3.5.1
    - mistune==0.8.4
    - msgpack==1.0.3
    - nbclient==0.5.13
    - nbconvert==6.4.5
    - nbformat==5.2.0
    - networkx==2.6.3
    - niet==2.4.0
    - notebook==6.4.10
    - pandocfilters==1.5.0
    - partd==1.2.0
    - patsy==0.5.2
    - pglast==3.9
    - pillow==9.0.1
    - prometheus-client==0.13.1
    - psycopg2-binary==2.9.3
    - pycodestyle==2.8.0
    - pyflakes==2.4.0
    - pyrsistent==0.18.1
    - python-graphviz==0.19.1
    - pyyaml==5.1
    - qtconsole==5.3.0
    - qtpy==2.0.1
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.1
    - sql-metadata==2.3.0
    - sqlparse==0.4.2
    - statsmodels==0.13.2
    - tblib==1.7.0
    - terminado==0.13.3
    - testpath==0.6.0
    - toolz==0.11.2
    - torchsummaryx==1.3.0
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - xgboost==1.5.2
    - xlrd==2.0.1
    - zict==2.1.0
prefix: /Users/jackiedong/opt/anaconda3/envs/db

